export const POST_TOPIC_REQUEST = "POST_TOPIC_REQUEST";
export const POST_TOPIC_SUCCESS = "POST_TOPIC_SUCCESS";
export const POST_TOPIC_FAIL = "POST_TOPIC_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const ALL_TOPIC_REQUEST = "ALL_TOPIC_REQUEST";
export const ALL_TOPIC_SUCCESS = "ALL_TOPIC_SUCCESS";
export const ALL_TOPIC_FAIL = "ALL_TOPIC_FAIL";

export const TOPIC_DETAILS_REQUEST = "TOPIC_DETAILS_REQUEST";
export const TOPIC_DETAILS_SUCCESS = "TOPIC_DETAILS_SUCCESS";
export const TOPIC_DETAILS_FAIL = "TOPIC_DETAILS_FAIL";

export const TOPIC_REPLY_REQUEST = "TOPIC_REPLY_REQUEST";
export const TOPIC_REPLY_SUCCESS = "TOPIC_REPLY_SUCCESS";
export const TOPIC_REPLY_FAIL = "TOPIC_REPLY_FAIL";
export const TOPIC_REPLY_RESET = "TOPIC_REPLY_RESET";

export const TOPIC_UPVOTE_REQUEST = "TOPIC_UPVOTE_REQUEST";
export const TOPIC_UPVOTE_SUCCESS = "TOPIC_UPVOTE_SUCCESS";
export const TOPIC_UPVOTE_FAIL = "TOPIC_UPVOTE_FAIL";
export const TOPIC_UPVOTE_RESET = "TOPIC_UPVOTE_RESET";

export const TOPIC_DOWNVOTE_REQUEST = "TOPIC_DOWNVOTE_REQUEST";
export const TOPIC_DOWNVOTE_SUCCESS = "TOPIC_DOWNVOTE_SUCCESS";
export const TOPIC_DOWNVOTE_FAIL = "TOPIC_DOWNVOTE_FAIL";
export const TOPIC_DOWNVOTE_RESET = "TOPIC_DOWNVOTE_RESET";

export const TOPIC_REPLY_UPVOTE_REQUEST = "TOPIC_REPLY_UPVOTE_REQUEST";
export const TOPIC_REPLY_UPVOTE_SUCCESS = "TOPIC_REPLY_UPVOTE_SUCCESS";
export const TOPIC_REPLY_UPVOTE_FAIL = "TOPIC_REPLY_UPVOTE_FAIL";
export const TOPIC_REPLY_UPVOTE_RESET = "TOPIC_REPLY_UPVOTE_RESET";

export const TOPIC_REPLY_DOWNVOTE_REQUEST = "TOPIC_REPLY_DOWNVOTE_REQUEST";
export const TOPIC_REPLY_DOWNVOTE_SUCCESS = "TOPIC_REPLY_DOWNVOTE_SUCCESS";
export const TOPIC_REPLY_DOWNVOTE_FAIL = "TOPIC_REPLY_DOWNVOTE_FAIL";
export const TOPIC_REPLY_DOWNVOTE_RESET = "TOPIC_REPLY_DOWNVOTE_RESET";
